"""empty db

Revision ID: 20161115T18:23:40
Revises:
Create Date: 2016-11-15 18:23:40.235614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20161115T18:23:40'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('id', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('gcp_project_id', sa.String(length=100), nullable=False),
                    sa.Column('code', sa.String(length=100), nullable=False),
                    sa.Column('date_deleted', sa.DateTime(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('latest_table_time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('ta',
                    sa.Column('id', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=True),
                    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failure', name='taliststatus'), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_deleted', sa.DateTime(), nullable=True),
                    sa.Column('target_type', sa.String(length=100), nullable=True),
                    sa.Column('product', sa.String(length=100), nullable=True),
                    sa.Column('bq_table', sa.String(length=100), nullable=True),
                    sa.Column('date_for_calculate', sa.DateTime(), nullable=True),
                    sa.Column('date_campaign_start', sa.DateTime(), nullable=True),
                    sa.Column('date_campaign_end', sa.DateTime(), nullable=True),
                    sa.Column('target_member_required', sa.String(length=100), nullable=True),
                    sa.Column('member_email_required', sa.Boolean(), nullable=True),
                    sa.Column('member_mobile_required', sa.Boolean(), nullable=True),
                    sa.Column('exclude_talist', sa.String(length=100), nullable=True),
                    sa.Column('group_id', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=True),
                    sa.Column('name', sa.String(length=10), nullable=True),
                    sa.Column('password', sa.String(length=50), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('auth', sa.Boolean(), nullable=True),
                    sa.Column('group_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ## end Alembic commands ###


def downgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ta')
    op.drop_table('group')
    # ## end Alembic commands ###
