"""added two columns to person table

Revision ID: 3715f217a003
Revises:
Create Date: 2016-11-09 15:54:15.280871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '3715f217a003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ## commands auto generated by Alembic - please adjust! ###
    # op.add_column('person', sa.Column('idcard', sa.String(length=20), nullable=True))
    # op.add_column('person', sa.Column('realname', sa.String(length=64), nullable=True))
    # ## end Alembic commands ###
    person_table = table('person',
                         column('person_id', sa.Integer),
                         column('nickname', sa.String(64)),
                         column('gender', sa.Integer),
                         column('idcard', sa.String(20))
                         )
    telephone_table = table('telephone',
                            column('tel_id', sa.Integer),
                            column('person_id', sa.Integer),
                            column('telphone_no', sa.String(64)),
                            column('memo', sa.String(20))
                            )
    data = [{'person_id': 1, 'nickname': 'kw', 'gender': 1, 'idcard': 'ppp123'},
            {'person_id': 2, 'nickname': 'jlin', 'gender': 0, 'idcard': 'jjj123'}
            ]

    tel = [{'tel_id': 1, 'telphone_no': '1234', 'person_id': 2, 'memo': ''},
           {'tel_id': 2, 'telphone_no': '5678', 'person_id': 1, 'memo': 'nba'}
           ]
    op.bulk_insert(person_table, data)
    op.bulk_insert(telephone_table, tel)


def downgrade():
    # sqlite is not support drop
    # op.drop_tabel('person', 'realname')
    # op.drop_column('person', 'idcard')
    op.drop_table('person')
    op.create_table('person',
                    sa.Column('person_id', sa.Integer, primary_key=True),
                    sa.Column('nickname', sa.String(64), nullable=False),
                    sa.Column('gender', sa.Integer),
                    sa.Column('idcard', sa.String(20))
                    )

    op.drop_table('telephone')
    op.create_table('telephone',
                    sa.Column('tel_id', sa.Integer, primary_key=True),
                    sa.Column('person_id', sa.Integer, sa.ForeignKey('person.person_id')),
                    sa.Column('telphone_no', sa.String(64)),
                    sa.Column('memo', sa.String(20))
                    )
